name: unichat_ai
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+4

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  cupertino_icons: ^1.0.2
  dart_openai: ^1.9.7
  flutter_chat_ui: ^1.6.6
  flutter_keyboard_visibility: ^5.0.2
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  google_sign_in: ^6.1.5
  flutter_signin_button: ^2.0.0
  shared_preferences: ^2.0.7
  in_app_purchase: ^3.1.10
  flutter_tts: ^3.8.3
  cloud_functions: ^4.4.1
  loading_animation_widget: ^1.2.0+4
  url_launcher: ^6.1.14
  device_info: ^2.0.3
  cloud_firestore: ^4.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/


